### PR TITLE
Ap 51 create create post form react component

### PR DESCRIPTION
**Pull request by ry-mchugh**
Created a JS component to create a post form on for the feed. 
Have created a button that allows a user to create a new post, this new post will then display on the screen once created.

### CODE REVIEW

**Review by murat-zsertay — CHANGES_REQUESTED** [review]
The code does not work on firefox only on chrome, 
the issue seems to be this (its coming up on the firefox console) -> Feature Policy: Skipping unsupported feature name “publickey-credentials-get”.

**Comment by ry-mchugh** [comment]
Hadn't tried on Firefox. Just downloaded it now and have been able to create a post/load the page without any errors or issues.

**Comment by ry-mchugh** [comment]
43CFDE71-2258-428C-9412-3C860C6B59D5

**Review by ry-mchugh — COMMENTED** [review]
No changes to be made. Tested on firefox and encountered no issues.

**Review by charlie-lam — APPROVED** [review]
Okay

**Review by murat-zsertay — APPROVED** [review]

**Review by tlchambers — APPROVED** [review]

**Pull request merged**
